/* eslint-disable import/prefer-default-export */

export const FEATURE_TYPES = {
  LAND_LOT: 1,
  LAND_QUARTER: 2,
  LAND_AREA: 3,
  LAND_DISTRICT: 4,
  CCO: 5,
  TERRITORIAL_AREA: 6,
  BOUNDARY: 7,
  BOUNDARY_REFERENCE_NETWORK: 9,
  USE_RESTRICTED_ZONE: 10,
  FORESTRY: 12,
  BUILDING_LINE: 13,
  LAND_LOT_LAYOUT: 15,
  FREE_ECONOMIC_ZONE: 16,
};
